# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://app.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}_2
        WS_PROJECTNAME: ${{github.event.repository.name}}_Prioritize
        WS_ENABLEIMPACTANALYSIS: true
        WS_REQUIREKNOWNSHA1: false
        WS_RESOLVEALLDEPENDENCIES: false
        WS_MAVEN_RESOLVEDEPENDENCIES: true
        WS_MAVEN_AGGREGATEMODULES: true
        WS_FILESYSTEMSCAN: false
        WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        WARFILE=$(find ./ -type f -wholename "*/target/*.war")
        java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
        # echo publish effective vulnerability links
        # chmod +x ./scripts/ghissue-eua.sh && ./scripts/ghissue-eua.sh
